velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0  # Rate to run smoother
    scale_velocities: false  # scale velocities proportionally if any axis is outside of acceleration range to follow same vector, if possible
    feedback: "OPEN_LOOP"  # Type of feedback for current speed. Open loop uses the last smoothed output. Closed loop uses robot odometry
    max_velocity: [10.5, 10.5, 10.5]  # Maximum velocities, ordered [Vx, Vy, Vw]
    min_velocity: [-10.5, -10.5, -10.5]  # Minimum velocities, ordered [Vx, Vy, Vw]
    deadband_velocity: [0.0, 0.0, 0.0]  # A deadband of velocities below which they should be zero-ed out for sending to the robot base controller, ordered [Vx, Vy, Vw]
    velocity_timeout: 1.0  # Time (s) after which if no new velocity commands are received to zero out and stop
    max_accel: [1.5, 1.5, 1.5]  # Maximum acceleration, ordered [Ax, Ay, Aw]
    max_decel: [-1.5, -1.5, -1.5]  # Maximum deceleration, ordered [Ax, Ay, Aw]
    odom_topic: "odom"  # Topic of odometry to use for estimating current velocities
    odom_duration: 0.1  # Period of time (s) to sample odometry information in for velocity estimation
    enable_stamped_cmd_vel: True # Whether to stamp the velocity. True uses TwistStamped. False uses Twist
    stamp_smoothed_velocity_with_smoothing_time: false # Whether to smooth the timestamp of the header message of TwistStamped output instead of keeping the timestamp of the last received command
