// https://gcc.gnu.org/wiki/Visibility
#ifndef HOLONOMIC_HOVER_CONTROLLER_LIBRARY__VISIBILITY_CONTROL_H_
#define HOLONOMIC_HOVER_CONTROLLER_LIBRARY__VISIBILITY_CONTROL_H_

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_EXPORT __attribute__((dllexport))
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_IMPORT __attribute__((dllimport))
#else
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_EXPORT __declspec(dllexport)
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_IMPORT __declspec(dllimport)
#endif
#ifdef HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_BUILDING_DLL
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_PUBLIC                          \
  HOLONOMIC_ROVER_CONTROLLER__VISIBILITY_EXPORT
#else
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_PUBLIC                          \
  HOLONOMIC_ROVER_CONTROLLER__VISIBILITY_IMPORT
#endif
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_PUBLIC_TYPE                     \
  HOLONOMIC_ROVER_CONTROLLER__VISIBILITY_PUBLIC
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_LOCAL
#else
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_EXPORT                          \
  __attribute__((visibility("default")))
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_IMPORT
#if __GNUC__ >= 4
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_PUBLIC                          \
  __attribute__((visibility("default")))
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_PROTECTED                       \
  __attribute__((visibility("protected")))
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_LOCAL                           \
  __attribute__((visibility("hidden")))
#else
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_PUBLIC
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_LOCAL
#endif
#define HOLONOMIC_HOVER_CONTROLLER__VISIBILITY_PUBLIC_TYPE
#endif

#endif // HOLONOMIC_HOVER_CONTROLLER_LIBRARY__VISIBILITY_CONTROL_H_
